
import './globals.css'
import './page.css'

import Navbar from './navbar'
import Footer from './footer'
export const metadata = {
  title: 'Bobolink',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar> 
          {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
